-- --------------------------------------------------------------------------------------
--
--   ██╗██╗  ██╗   ██╗ █████╗ ███╗   ███╗██╗██████╗  ██████╗
--   ██║██║  ╚██╗ ██╔╝██╔══██╗████╗ ████║██║██╔══██╗██╔═══██╗
--   ██║██║   ╚████╔╝ ███████║██╔████╔██║██║██████╔╝██║   ██║
--   ██║██║    ╚██╔╝  ██╔══██║██║╚██╔╝██║██║██╔══██╗██║   ██║
--   ██║███████╗██║   ██║  ██║██║ ╚═╝ ██║██║██║  ██║╚██████╔╝
--   ╚═╝╚══════╝╚═╝   ╚═╝  ╚═╝╚═╝     ╚═╝╚═╝╚═╝  ╚═╝ ╚═════╝
--
--   Created by ilyamiro
--   https://github.com/ilyamiro/nixos-configuration
--
--   Lua config (Hyprland >= 0.55). Colors are generated by matugen into colors.lua.
--
-- --------------------------------------------------------------------------------------

-- Clear cache to allow reloading
package.loaded["colors"] = nil
package.loaded["config.variables"] = nil
package.loaded["config.monitors"] = nil
package.loaded["config.plugins"] = nil
package.loaded["config.env"] = nil
package.loaded["config.autostart"] = nil
package.loaded["config.settings"] = nil
package.loaded["config.rules"] = nil
package.loaded["config.keybindings"] = nil

-- Register the passthru submap with a dummy bind so all normal keystrokes
-- fall through to Quickshell (mirrors the old `submap = passthru` block).
hl.define_submap("passthru", function()
    hl.bind("SUPER + SHIFT + CTRL + ALT + F35", hl.dsp.exec_cmd("true"))
end)

-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
--  ◈ MODULAR CONFIGURATION (each module mirrors the old sourced *.conf files)
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

require("config.variables")
require("config.monitors")
require("config.plugins")
require("config.env")
require("config.autostart")
require("config.settings")
require("config.rules")
require("config.keybindings")
