-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
--  ◈ PLUGIN LOADING & CONFIG (hyprglass)
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
--
-- DO NOT CALL hl.plugin.load() FROM HERE. DO NOT ADD IT BACK.
--
-- Hyprland 0.56.1 has unbounded recursion in its config-reload path:
--   CConfigManager::reload()
--     -> postConfigReload()
--       -> handlePluginLoads()      (calls reload() again if pluginsChanged)
--         -> reload() -> ... forever
-- CPluginSystem::updateConfigPlugins() only early-returns when the config
-- plugin list is byte-identical to the previous reload. Loading a plugin from
-- inside the config makes that list unstable, so pluginsChanged stays true on
-- every pass. The recursion is synchronous, so it starves the event loop that
-- the async plugin load needs in order to ever complete. Result: stack
-- exhaustion -> SIGSEGV -> the whole Wayland session dies and drops you at the
-- SDDM login screen with every app killed.
--
-- hyprglass is therefore loaded and configured OUTSIDE the config reload path
-- by scripts/hyprglass_startup.sh (hyprctl plugin load + hyprctl setconfig),
-- which runs from autostart. See that script for the actual settings.
--
-- This module is intentionally empty. It is kept because hyprland.lua
-- requires it and because it documents the crash above.

return true