-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
--  ◈ SETTINGS (AUTOGENERATED FROM SETTINGS.JSON)
-- ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

local colors = require "colors"

hl.config({
    general = {
        border_size = 2,
        gaps_in = 4,
        gaps_out = 4,
        float_gaps = 6,
        resize_on_border = true,
        extend_border_grab_area = 30,
        col = {
            active_border = colors.active_border,
            inactive_border = colors.inactive_border
        }
    },

    decoration = {
        rounding = 10,
        active_opacity = 1.0,
        inactive_opacity = 0.97,
        blur = {
            enabled = true,
            size = 8,
            passes = 2,
            new_optimizations = true
        },
        shadow = {
            enabled = true,
            range = 14,
            render_power = 3,
            color = "0x00000073",
            color_inactive = "0x0000004d"
        }
    },

    input = {
        kb_layout = "us",
        kb_options = "grp:alt_shift_toggle",

        touchpad = {
            natural_scroll = true
        }
    },

    cursor = {
        no_warps = true
    },

    misc = {
        font_family = "JetBrains Mono",
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        force_default_wallpaper = 0,
        -- VRR always-on caused flicker/black frames on this panel; 0 = off (stable)
        vrr = 0,
        -- Hyprland is launched directly (not via start-hyprland) to avoid a
        -- teardown crash; silence the advisory warning about it.
        disable_watchdog_warning = true
    },

    ecosystem = {
        no_update_news = true,
        no_donation_nag = true
    },

    -- Require a small mouse travel before a SUPER+drag "picks up" a window,
    -- so a plain hold/click doesn't float-then-retile the window (flicker).
    binds = {
        drag_threshold = 10
    },

    animations = {
        enabled = true
    }
})

-- ── Curves (beziers) ──
hl.curve("easeOutExpo", { type = "bezier", points = { { 0.16, 1 }, { 0.3, 1 } } })
hl.curve("snappy", { type = "bezier", points = { { 0.05, 0.9 }, { 0.1, 1.05 } } })
hl.curve("overshoot", { type = "bezier", points = { { 0.05, 1.2 }, { 0.15, 1.02 } } })
hl.curve("soft", { type = "bezier", points = { { 0.4, 0 }, { 0.2, 1 } } })

-- ── Animations ──
hl.animation({ leaf = "windows", enabled = true, speed = 5, bezier = "overshoot", style = "popin 90%" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 5, bezier = "overshoot", style = "popin 90%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 4, bezier = "easeOutExpo", style = "popin 85%" })
hl.animation({ leaf = "windowsMove", enabled = true, speed = 4, bezier = "overshoot", style = "slide" })
hl.animation({ leaf = "fade", enabled = true, speed = 4, bezier = "soft" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 4, bezier = "soft" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 4, bezier = "soft" })
hl.animation({ leaf = "fadeSwitch", enabled = true, speed = 4, bezier = "soft" })
hl.animation({ leaf = "fadeDim", enabled = true, speed = 5, bezier = "soft" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 6, bezier = "easeOutExpo", style = "slide" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 6, bezier = "easeOutExpo", style = "slide" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 6, bezier = "easeOutExpo", style = "slide" })
hl.animation({ leaf = "border", enabled = true, speed = 8, bezier = "snappy" })
hl.animation({ leaf = "borderangle", enabled = true, speed = 8, bezier = "snappy" })
hl.animation({ leaf = "layers", enabled = true, speed = 5, bezier = "easeOutExpo", style = "fade" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 5, bezier = "easeOutExpo", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 5, bezier = "easeOutExpo", style = "fade" })
hl.animation({ leaf = "specialWorkspace", enabled = true, speed = 5, bezier = "easeOutExpo", style = "slidefade" })
hl.animation({ leaf = "specialWorkspaceIn", enabled = true, speed = 5, bezier = "easeOutExpo", style = "slidefade" })
hl.animation({ leaf = "specialWorkspaceOut", enabled = true, speed = 5, bezier = "easeOutExpo", style = "slidefade" })
